//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDiaryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.fuel_consumption = new HashSet<fuel_consumption>();
            this.other_costs = new HashSet<other_costs>();
        }
    
        public car(string brand, string model, int year,string engine, string fuel, int h_powers,string image, string user)
        {
            this.brand = brand;
            this.model = model;
            this.year = year;
            this.engine = engine;
            this.fuel = fuel;
            this.h_powers = h_powers;
            this.image = image;
            this.user_name = user;
        }

        public int id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public int year { get; set; }
        public string engine { get; set; }
        public string fuel { get; set; }
        public int h_powers { get; set; }
        public string image { get; set; }
        public string user_name { get; set; }
        public byte[] blobimage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fuel_consumption> fuel_consumption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<other_costs> other_costs { get; set; }
    }
}
