//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDiaryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_diary_log
    {
        public int id { get; set; }
        public System.DateTime operation_dtm { get; set; }
        public string operation { get; set; }
        public string table_name { get; set; }
        public string ip_user { get; set; }
    }
}
